version: "3"
services:
  cloudmake-registry:
    ports:
      - '5000:5000/tcp'
    networks:
      - kubeadm-dind-net-cloudmake
  push-image:
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      IMAGE: ${IMAGE}
      REGISTRY: ${REGISTRY}
networks:
  kubeadm-dind-net-cloudmake:
    external: True
