version: "3"
services:
  hyper-app:
    build:
      context: '../..'
      dockerfile: './docker/dev/Dockerfile'
    volumes:
      - '../../src:/app/src'
    ports:
      - '${APP_PORT:-8000}:8000/tcp'
