apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose -f /home/bbubu/projects/cloudmake-examples/actix-app/ops/k8s/prod/.stack.yml
      -o /home/bbubu/projects/cloudmake-examples/actix-app/ops/k8s/prod convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: actix-app
  name: actix-app
spec:
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8088
  selector:
    io.kompose.service: actix-app
status:
  loadBalancer: {}
